### ISSUE TITLE
Error when calling getTransactionInfo

### ISSUE THREAD

**Issue by nborggren** [ItsAditya-xyz/DeSo.py#32]
#It seems that the API may have changed for getTransactionInfo (8. on the DeSo.py documentation)

import deso
desoUser = deso.User()
userPublicKey = "BC1YLhBLE1834FBJbQ9JU23JbPanNYMkUsdpJZrFVqNGsCe7YadYiUg"
print(desoUser.getTransactionInfo(userPublicKey).json())

error:
JSONDecodeError: [Errno Extra data] 404 page not found

**Comment by melzubeir** [comment]
The arguments you mention are available to use, although not documented. 
```
    def getTransactionInfo(
        self,
        publicKey,
        limit=200,
        lastTransactionIDBase58Check="",
        lastPublicKeyTransactionIndex=-1,
    ):
```

Also, what version are you using, because I'm unable to replicate your error (see below).

![Screenshot from 2023-01-26 20-43-23](https://user-images.githubusercontent.com/66845648/214999117-bfd9cf72-5148-4f09-99eb-59c7f5848648.png)

**Comment by nborggren** [comment]
using:
deso                      2.0.8                    pypi_0    pypi
I'll try updating and seeing if that fixes it

**Comment by melzubeir** [comment]
you're some way out there buddy lol

**Comment by nborggren** [comment]
indeed, thought I did update, but alas no.  Cheers.
